name: 'Trigger binder build'
description: 'Triggers the build of a repository on mybinder.org'
author: 'Sebastian Weigand'
inputs:
  target-repo:
    description: 'Repository which should be build'
    required: true
  service-name:
    description: "gh|gist|gl|git|zenodo|figshare Name of the service that hosts the repo. Default: 'gh'"
    required: false
    default: gh
  target-state:
    description: "Name of the branch, tag or commit which should be build. Default: ''"
    required: false
    default: ''
  use-default-build-servers:
    description: 'Whether or not to use the default mybinder.org build servers. If false and additional-build-server is not specified, this will throw an error. Default: true'
    required: false
    default: true
  additional-build-servers:
    description: "Newline separated list of urls, which point do binder build servers base url. Default: ''"
    required: false
    default: ''
  debug:
    description: 'Weather to print debug information or not. Default: false'
    required: false
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'code'
  color: 'yellow'
