name: 'Tests'
on: [push, pull_request]

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test Build
        run: npm run test_build
      - name: Checking format
        run: npm run format-check
      - name: Linting code
        run: npm run lint
      - name: Running jest tests
        run: npm test
      - name: Codecov Upload
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage/lcov.info
